stages:
    - setup
    - base
    - node
    - deploy

.template: &template
    services: 
        - docker:dind
    image: docker
    tags:
        - docker
    script:
        - cd $CONTAINER_NAME
        - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
        - docker build -t registry.gitlab.com/viper-staking/docker-containers/$CONTAINER_NAME:latest .
        - docker push registry.gitlab.com/viper-staking/docker-containers/$CONTAINER_NAME:latest
        - cd ..

remove-submodules:
    stage: setup
    script:
        # Remove submodule dir (workaround for GitLab bug)
        - if [ -d debian-base/shared-terminal-settings ]; then rm -rf debian-base/shared-terminal-settings; fi
        - if [ -d cardano-node/cardano-tools ]; then rm -rf cardano-node/cardano-tools; fi

debian-base:
    <<: *template
    stage: base
    variables:
        CONTAINER_NAME: debian-base
        GIT_SUBMODULE_STRATEGY: recursive
    before_script:
        - ls $CONTAINER_NAME/shared-terminal-settings

cardano-node:
    <<: *template
    stage: node
    variables:
        CONTAINER_NAME: cardano-node
        GIT_SUBMODULE_STRATEGY: recursive
    before_script:
        - ls $CONTAINER_NAME/cardano-tools

jormungandr:
    <<: *template
    stage: node
    variables:
        CONTAINER_NAME: jormungandr
