stages:
    - base
    - node
    - deploy

.template: &template
    services: 
        - docker:dind
    image: docker
    tags:
        - docker
    script:
        - cd $CONTAINER_NAME
        - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
        - docker build -t registry.gitlab.com/viper-staking/docker-containers/$CONTAINER_NAME:latest .
        - docker push registry.gitlab.com/viper-staking/docker-containers/$CONTAINER_NAME:latest
        - cd ..

debian-base:
    <<: *template
    stage: base
    variables:
        CONTAINER_NAME: debian-base
        GIT_SUBMODULE_STRATEGY: none

cardano-node:
    <<: *template
    stage: node
    variables:
        CONTAINER_NAME: cardano-node

jormungandr:
    <<: *template
    stage: node
    variables:
        CONTAINER_NAME: jormungandr
