stages:
   - build

debian-base:
   stage: build
   services: 
      - docker:dind
   image: docker
   tags:
      - docker
   script:
      - docker build -t registry.gitlab.com/viper-staking/docker-containers/debian-base:latest ./debian/base
      - docker push registry.gitlab.com/viper-staking/docker-containers/debian-base:latest
